version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: SANITY_AUTH_TOKEN=$SANITY_DEPLOY_STUDIO_TOKEN yarn deploy
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: main
